### ISSUE TITLE
Typed fields should take defaults for empty values

### ISSUE THREAD

**Issue by alex-schneider** [filex/echo-json#2]
For example, `echo-json foo:int ""` produces an `invalid syntax` error like:

`json encode error: Argument Error: value () for key "foo" is not an int: strconv.ParseInt: parsing "": invalid syntax`

Expected result: `{"foo":0}` like for `echo-json foo:int` (<--- w/o a value)

**Comment by filex** [comment]
good idea :)

new behaviour:

```
$ echo-json foo:int "" 
{"foo":0}
```
