### ISSUE TITLE
no html escaping

### ISSUE THREAD

**Issue by malud** [filex/echo-json#5]
`echo-json` escapes html chars (`&<>`)

```
❯ go run echo-json.go asdf "value&asdf>"
{"asdf":"value\u0026asdf\u003e"}
```

expected: `{"asdf": "value&asdf>"}`

Maybe as escape option which is disabled by default.

See: https://golang.org/pkg/encoding/json/#Encoder.SetEscapeHTML

**Comment by filex** [comment]
solved in #6
